// WEB3 REDUCER
export const SET_WEB3_INSTANCE = 'SET_WEB3_INSTANCE';
export const SET_WEB3_READ_INSTANCE = 'SET_WEB3_READ_INSTANCE';
export const ADD_CONTRACT = 'ADD_CONTRACT';
export const SET_INITIALIZED = 'SET_INITIALIZED';
export const SET_ETH_INJECTED = 'SET_ETH_INJECTED';

// TX HANDLER
export const TX_LOADING = 'TX_LOADING';
export const TX_FAILED = 'TX_FAILED';
export const TX_SUCCESS = 'TX_SUCCESS';
export const SET_LOADING_MINT_DATA = 'SET_LOADING_MINT_DATA';
export const SET_MINT_DATA = 'SET_MINT_DATA';
export const SET_AMOUNT = 'SET_AMOUNT';

//WALLET REDUCER
export const SET_WALLET = 'SET_WALLET';
export const SET_CHAIN_ID = 'SET_CHAIN_ID';
export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS';
